id: P006637
initial_creation_type: ocr
source_metadata:
  id: bdr:W27021
  title: གྲུབ་ཆེན་ནམ་མཁའ་རྒྱལ་མཚན་གྱི་མཛད་རྣམ་ཐོར་བུ་དང་ན་སྟེང་དང་བཀྲ་ཤིས་གླིང་དགོན་གྱི་དཀར་ཆག་དོན་གསལ་མེ་ལོང
  author: ''
  volumes:
    fb40a835fb774049b24018e974463a0c:
      image_group_id: I1PD30384
      title: ''
      volume_number: 1
      total_pages: 238
