id: opecha:P006637
initial_creation_type: ocr
source_metadata:
  id: bdr:W27021
  title: གྲུབ་ཆེན་ནམ་མཁའ་རྒྱལ་མཚན་གྱི་མཛད་རྣམ་ཐོར་བུ་དང་ན་སྟེང་དང་བཀྲ་ཤིས་གླིང་དགོན་གྱི་དཀར་ཆག་དོན་གསལ་མེ་ལོང
  volume: ''
  author: ''
